server {
    listen 80;
    server_name localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # Esto redirige cualquier petición al index.html para que React Router tome el control
        try_files $uri $uri/ /index.html;
    }

    # Opcional: Habilitar compresión Gzip para que cargue más rápido
    gzip on;
    gzip_types text/plain application/javascript application/x-javascript text/javascript text/xml text/css;
}